---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: wasm-plugin
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httpbin
  wasm:
  - code:
      type: Image
      image:
        url: us-central1-docker.pkg.dev/eitan-tetrate/misc-repo/wasm:v1
    config:
      header_1: my first header
      header_2: "yet another header.."


