---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  hostnames:
  - httpbin.esuez.org
  parentRefs:
  - name: eg
  rules:
  - backendRefs:
    - name: httpbin
      port: 8000
